name: diarize
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.10
  - pip

  # audio conversion
  - ffmpeg

  # python soundfile module (import soundfile)
  - pysoundfile

  # numeric stack (avoid MKL via conda-forge)
  - numpy<2
  - scipy

  # pytorch stack (CPU)
  - pytorch
  - torchaudio

  # misc
  - pandas
  - tqdm

  - pip:
      - "huggingface_hub==0.25.2"
      - "pyannote.audio==3.4.0"
      - "openai-whisper"